import type { Metadata } from "next";
import { Raleway } from "next/font/google";


import "./globals.css";
import Header from "./components/header";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <section className="navigation">
          <Header />
        </section>
        <main className="main">
          {children}
        </main>
        <footer className="footer"></footer>
      </body>
    </html>
  );
}
