import type { Metadata } from "next";
import { Ibarra_Real_Nova } from "next/font/google";
import { UserProvider } from '@auth0/nextjs-auth0/client';


import "./globals.css";
import Header from "./components/header";

const ibarra = Ibarra_Real_Nova({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={ibarra.className}>
          <section className="navigation">
            <Header />
          </section>
          <main className="main">
            {children}
          </main>
          <footer className="footer"></footer>
        </body>
      </UserProvider>
    </html>
  );
}
