import type { Metadata } from "next";
import { Ibarra_Real_Nova } from "next/font/google";
import "./globals.css";

const ibarra = Ibarra_Real_Nova({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ibarra.className}>
        <nav className="navigation"></nav>
        <main className="main">
          {children}
        </main>
        <footer className="footer"></footer>
      </body>
    </html>
  );
}
